server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezon=Asia/Seoul
    username: cos
    password: cos1234

  mvc:
    view:
      prefix: /template/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 619212129094-amoius4pu5v54e0utvnfov57be5lu8lt.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

