server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    hibernate:
      ddl-auto: update #create update none. update로 하면 기록 유지.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 944673088660-luse034h8a2htiohtk99dfkj7ks0401a.apps.googleusercontent.com
            client-secret: wzR7Sw2ahBYnBIe4u-IEdwcj
            scope:
            - email
            - profile
          facebook:
            client-id: 1125866391234236
            client-secret: eba74d5c4e0dd2c6de2696f0f59e0f58
            scope:
            - email
            - public_profile
          naver:
            client-id: ??
            client-secret: ??
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver